FROM ghcr.io/cross-rs/x86_64-pc-windows-gnu:main
ARG DEBIAN_FRONTEND=noninteractive

COPY cross/sccache-from-source.sh /sccache.sh
RUN /sccache.sh x86_64-pc-windows-gnu

ENV RUSTC_WRAPPER="/usr/bin/sccache"
