name: "Build and Release"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Nix
      uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
            ./result/bin/qremote
